insert into ADDRESS (city) values ('Austin');
insert into ADDRESS (city) values ('Dallas');
insert into ADDRESS (city) values ('Los Angeles');
insert into ADDRESS (city) values ('New York');
insert into ADDRESS (city) values ('Orlando');
insert into ADDRESS (city) values ('San Francisco');
insert into PERSON (first_name, last_name, birth_date, address_id) values ('Jon', 'Tian','2000-01-01 12:30:00',1);
insert into PERSON (first_name, last_name, birth_date, address_id) values ('Jon_1', 'Tian','2000-01-01 13:30:00',2);
insert into PERSON (first_name, last_name, birth_date, address_id) values ('Jon_2', 'Tian','2000-01-01 14:30:00',3);
insert into PERSON (first_name, last_name, birth_date, address_id) values ('Jon_3', 'Tian','2000-01-01 15:30:00',4);
insert into PERSON (first_name, last_name, birth_date, address_id) values ('Jon_4', 'Tian','2000-01-01 16:30:00',5);
insert into PERSON (first_name, last_name, birth_date, address_id) values ('Jon_5', 'Tian','2000-01-01 17:30:00',6);
