CREATE TABLE PERSON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	address_id int null
);
CREATE TABLE ADDRESS (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	city varchar(255) not null
);

CREATE TABLE Test_Entity (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,

     util_date DATETIME null,
     sql_date DATETIME null,
     string varchar null,
     big_decimal decimal null,
     a_char char(1) null,
     a_long bigint null,
     a_integer int null,
     a_double double null,
     a_float float null,
     a_boolean boolean null,
);
