CREATE TABLE Test_Entity (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,

     util_date DATETIME not null,
     sql_date DATETIME not null,
     string varchar not null,
     big_decimal decimal not null,
     a_char char(1) not null,
     a_long bigint not null,
     a_integer int null,
     a_double double null,
     a_float float not null,
     a_boolean binary not null,
);
